<?php
/**
 * Copyright (c) 2016 Pepperjam Network.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Pepperjam Network
 * Magento Extensions End User License Agreement
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://assets.pepperjam.com/legal/magento-connect-extension-eula.pdf
 *
 * @copyright   Copyright (c) 2016 Pepperjam Network. (http://www.pepperjam.com/)
 * @license     http://assets.pepperjam.com/legal/magento-connect-extension-eula.pdf  Pepperjam Network Magento Extensions End User License Agreement
 */
?>

<?php if ($this->showBeacon()) :
?>
    <?php $beaconUrl = $this->getBeaconUrl(); ?>
    <script>
        (function (d,i) {
            i=d.createElement('iframe');
            i.width=i.height=1;
            i.frameBorder=0;
            i.src="<?php echo $beaconUrl; ?>";
            d.body.appendChild(i);
        }(document));
    </script>
    <noscript>
        <iframe width="1" height="1" frameBorder="0" src="<?php echo $beaconUrl; ?>"></iframe>
    </noscript>
<?php
endif;
