<?php
/**
 * Copyright (c) 2016 Pepperjam Network.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Pepperjam Network
 * Magento Extensions End User License Agreement
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://assets.pepperjam.com/legal/magento-connect-extension-eula.pdf
 *
 * @copyright   Copyright (c) 2016 Pepperjam Network. (http://www.pepperjam.com/)
 * @license     http://assets.pepperjam.com/legal/magento-connect-extension-eula.pdf  Pepperjam Network Magento Extensions End User License Agreement
 */
?>

<?php if ($this->injectJavaScript()) :
?>
    <?php $keyName = $this->getQueryStringKeyName(); ?>
    <?php $cookieName = $this->getCookieName(); ?>
    <script type="text/javascript">
        //<![CDATA[
        (function (window, document, duration_in_days, key_name, cookie_name) {
            var milliseconds_in_days = 1000 * 60 * 60 * 24;
            var query = location.search.substring(1);
            var source = findAffiliateField(query, key_name);
            var cookie = getCookie(cookie_name);

            if (source) {
                // set or update the cookie with the value from the current query string
                setCookie(cookie_name, source, duration_in_days);
            }

            /**
             * @param cname name of the cookie
             * @param cvalue value assigned to cookie
             * @param exdays duration of the cookie in days
             */
            function setCookie(cname, cvalue, exdays)
            {
                var d = new Date();
                d.setTime(d.getTime() + (exdays * milliseconds_in_days));
                var expires = "expires="+d.toUTCString();
                document.cookie = cname + "=" + cvalue + "; " + expires + "; path=/";
            }

            /**
             * @param cname name of the cookie
             * @returns object | null object with the field and value or null if not found
             */
            function getCookie(cname)
            {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var keyPair = cookies[i].split('=');
                    if (keyPair.length < 2)
                        continue;
                    var field = keyPair[0].trim();
                    var value = keyPair[1].trim();

                    if (field === cname) {
                        return {field: value};
                    }
                }

                return null;
            }

            /**
             * @param query query string  minus the '?'
             * @param field query string field to search for
             * @returns string | null value of the query string field or null if the field isn't there
             */
            function findAffiliateField(query, field)
            {
                if (!query) {
                    return null;
                }

                var fields = query.split("&");
                for (var i = 0; i < fields.length; i++) {
                    var keyPair = fields[i].split("=");
                    if (
                        keyPair.length == 2 &&
                        keyPair[0] === field
                    ) {
                        return keyPair[1];
                    }
                }

                return null;
            }
        }(window, document, 365, "<?php echo $keyName ?>", "<?php echo $cookieName ?>"));
        //]]>
    </script>
<?php
endif;
