<?php if ($this->showBeacon()):?>
	<?php $beaconUrl = $this->getBeaconUrl(); ?>
	<script>
		(function (d,i) {
			i=d.createElement('iframe');
			i.width=i.height=1;
			i.frameBorder=0;
			i.src="<?php echo $beaconUrl; ?>";
			d.body.appendChild(i);
		}(document));
	</script>
	<noscript>
		<iframe width="1" height="1" frameBorder="0" src="<?php echo $beaconUrl; ?>"></iframe>
	</noscript>
<?php endif?>