<?php
/**
 * Copyright (c) 2016 Pepperjam Network.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Pepperjam Network
 * Magento Extensions End User License Agreement
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://assets.pepperjam.com/legal/magento-connect-extension-eula.pdf
 *
 * @copyright   Copyright (c) 2016 Pepperjam Network. (http://www.pepperjam.com/)
 * @license     http://assets.pepperjam.com/legal/magento-connect-extension-eula.pdf  Pepperjam Network Magento Extensions End User License Agreement
 *
 */
?>

<script type="text/javascript">
function uninstall() {
	if (confirm('Prepare Pepperjam Network for uninstallation?')) {
		new Ajax.Request('<?php echo $this->getAjaxUninstallUrl(); ?>', {
			method: 'get',
			onSuccess: function(response) {
				document.location.reload(true);
			}
		});
	}
}
</script>

<?php echo $this->getButtonHtml(); ?>
